### ISSUE TITLE
Exporting ECMAScript module

### ISSUE THREAD

**Issue by alexhaller** [nibdo/ical-js-parser#8]
Hi,
I get the following warning when I compile my angular app and using ical-js-parser:

> Warning: <path>xyz.ts depends on 'ical-js-parser'. CommonJS or AMD dependencies can cause optimization bailouts.
> For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Would it be possible to export an ECMAScript module?
Thank you!

**Comment by nibdo** [comment]
Hello, 

please try new version 0.1.7, it should be fixed.

**Comment by alexhaller** [comment]
It works. Great support - many thanks!

**Comment by alexhaller** [comment]
Hi @nibdo,
the error occurs since around 0.2.0 or 0.4.0 again. Can you help?
Thanks!

**Comment by nibdo** [comment]
Hi @alexhaller, sorry for problems :/ I had to revert it because of some compatibility issues for my projects and I think for now it would be best to publish separate versions.

I have published latest one under name ical-js-parser-es
https://www.npmjs.com/package/ical-js-parser-es

If you need any specific previous version, I can republish it.

**Comment by alexhaller** [comment]
That´s great, thank you!
